use docval
arayabrain/barebone-studio pull request #131
Opened 2023-11-02 11:32 UTC by ReiHashimoto

docvalを使用して関数のドキュメントを生成するように試験的に改修
あくまで試験的な実装のため、caiman_mc, caiman_cnmfのみ対応し、他の関数は無効にしている

本実装方針で問題ない場合、以下の残タスクを対応予定
- [ ] 他のwrapper関数への適用
- [ ] 不要なファイル群の削除
- [ ] テストコードの改修
- [ ] 関数追加方法などのドキュメンテーションの修正
- [ ] wrapper関数のドキュメンテーションへの導線追加

## wrapper関数の実装方法

```python
# _以下のmoduleをimport
from hdmf.utils import docval, popargs
from studio.app.common.core.param.param import Param
from studio.app.common.core.wrapper.wrapper import Wrapper

# Wrapperクラスを継承してwrapper関数のクラスを定義する
class SomeFunction(Wrapper):
    # importしたParamクラスを使用して各種引数を定義する
    # ノードで入出力のコネクタとなるデータクラスを定義
    _INPUT_NODES = [
        Param(name="images", type=ImageData),
        # 接続しなくても良いOptionalなコネクタの場合は、default=Noneとする
        Param(name="iscell", type=IscellData, default=None)
    ]
    _OUTPUT_NODES = [Param(name="fluorescence", type=FluoData)]
    _DEFAULT_PARAMS = [
        Param(
            name="param1",
            type=str,  # typeはpythonの型をそのまま使用する
            default="param1_value",
            doc="param1_doc",
        ),
        # GUIで階層で表示させるパラメータの場合は、sectionを使用する。
        Param(
            name="param2",
            type=int,
            default=2,
            section="section_A",
            doc="param2_doc",
        ),
        # sectionは/を区切り文字として、ネストさせることができる。
        Param(
            name="param3",
            type=list,
            default=[3, 3],
            section="section_A/section_AA",
            doc="param3_doc",
        )
    ]
    
    # Snakemakeで実行する関数は名称をfuncとする
    # 関数にdocvalデコレータを使用し、_INPUT_NODES, _DEFAULT_PARAMSを展開して渡す
    # sectionなど、本来docvalに存在しない属性を使用しているため、コンバート用の関数を使用する
    # docvalによってパラメータが渡されるため、funcの引数はself, **kwargsとする
    @docval(*Wrapper.docval_params([*_INPUT_NODES, *_DEFAULT_PARAMS]))
    def func(self, **kwargs):
        """some_function
        
        ここに関数の概要を記載する
        """
        # output_dir, function_idはWrapperクラスで抱えているため、selfから取得できる
        print(self.output_dir)
        print(self.function_id)
        
        # nwbパラメータも同様にselfから取得できる
        # 元々引数として明示はなかったが、一部関数ではimaging_rateを取得するためにkwargsから取り出していた
        fr = self.nwb_params.get("imaging_plane", {}).get("imaging_rate", 30)
        
        # その他は変更点なし
        ...
```

wrapper_dictは以下のように変更
```python
# importするのが関数ではなくクラスになる
from studio.app.optinist.wrappers.some.some import SomeFunction

some_wrapper_dict = {
    "some": {
        "some_function": {
            # wrapper関数のクラスの**インスタンス**を渡す
            # ()が必要な点に注意
            "function": SomeFunction(),
            "conda_name": "some",
        }
    }
}
```

## documentの確認方法
以下のコマンドでshpinxをローカル起動
```bash
# installしていない場合のみ
pip install -e '.[doc]'

make docs
```
起動後に、以下のパスからcaimanのdocumentが参照可能
http://localhost:8001/modules/studio.app.optinist.wrappers.caiman.html
これらのdocumentへの導線追加は未対応

## その他
- 本改修に伴い、workflow.yamlおよびexperiment.yamlについて、パラメータ部分(snakemake, nwb, nodeパラメータ)のフォーマットが変わる(dataType, docなどの属性が追加されている)が、下位互換性を持たせているためversion1以降のexperimentは読み込み可能

2023-11-06 06:47 UTC, itutu-tienday requested changes
細かな指摘もありますが、
一旦いくつかフィードバックを行います。

2023-11-06 06:47 UTC, itutu-tienday commented on studio/app/optinist/wrappers/caiman/cnmf.py
>  from studio.app.optinist.dataclass import CaimanCnmfData, FluoData, IscellData, RoiData
Wapperを継承していない関数（ここでは get_roi()）は、ここで定義可能とするか？
→ CaimanCnmf 内からしか利用されていないと思われるため、CaimanCnmf に内包で良さそうかもしれない。（annotationなどで、internalな関数であることも示す）

2023-11-06 06:47 UTC, itutu-tienday commented on docs/modules/studio.app.common.core.auth.rst
> +studio.app.common.core.auth package
これらのファイル（.rst）は、事前に手動での作成を要するでしょうか。（自動生成できるものではない？）

2023-11-06 06:47 UTC, itutu-tienday commented on studio/app/common/core/wrapper/wrapper.py
> +class Wrapper:
このクラスについて、abstract化を検討しても良いのではないか？
https://docs.python.org/ja/3/library/abc.html

2023-11-06 06:47 UTC, itutu-tienday commented on studio/app/common/core/wrapper/wrapper.py
> +class Wrapper:
クラスの名称が Wrapper ですが、もう少し装飾しても良いかもしれない。 （機能的には Node,Algorithmのwrapper、ということかと思います）

2023-11-06 06:47 UTC, itutu-tienday commented on studio/app/common/core/wrapper/wrapper_utils.py
> +            return wrapper_dict[name]["function"]
（それほど重要ではないかもしれませんが、）
この "function" のキーワードは割と出現するようなので、定数化しておいても良いかもしれない。

2023-11-06 06:47 UTC, itutu-tienday commented on studio/app/common/core/experiment/experiment.py
> +    nwb: Dict[str, Union[ParamChild, ParamParent]]
これは質問ですが、
以下でデータタイプをあえて標準の Dict 化しているのは、どのような意図からでしたでしょうか。

2023-11-06 06:47 UTC, itutu-tienday commented on studio/app/common/routers/algolist.py
> +    def get_nest_dict(cls, parent_value, parent_key: str) -> AlgoList:
既知かと思いますが、現在、API documentページ（/docs）で /algolist へアクセスすると、ブラウザがフリーズするようです。
※FE（ブラウザ）側で、レスポンスのパース時にフリーズしているように見える。

また、他のAPIでも同様の事象が生じているようです。（/params 系など）

2023-11-06 06:51 UTC, itutu-tienday commented
@ReiHashimoto 

> 以下のコマンドでshpinxをローカル起動
> 
> ```
> # installしていない場合のみ
> pip install -e '.[doc]'
> make docs
> ```
> 

上記を試してみたところ、こちらの環境で以下のようなエラーが出ていますが、動作はしますでしょうか？
> $ cd {BAREBONE_INSTALL_DIR}
> $ make docs
> 
> rm -rf docs/_build/
> \# pip install -e '.[doc]'
> sphinx-apidoc -f --no-toc -o ./docs/modules ./studio
> make: sphinx-apidoc: No such file or directory
> make: *** [Makefile:35: docs] Error 127

2023-11-06 07:05 UTC, ReiHashimoto commented on studio/app/common/routers/algolist.py
> +    def get_nest_dict(cls, parent_value, parent_key: str) -> AlgoList:
こちらは既知の事象で、develop-mainでも同様に発生している状況です。
ただし、すべてのエンドポイントでデグレしていないかは未チェックで、このPRによってフリーズするようになっている箇所もありそうです。
algolist含め解消方法要調査かと思います。

2023-11-06 07:06 UTC, ReiHashimoto commented on studio/app/common/core/experiment/experiment.py
> +    nwb: Dict[str, Union[ParamChild, ParamParent]]
keyが定まっていないためこのような形式にしているのですが、betterな方法があればそちらに切り替えたいです。

2023-11-06 07:09 UTC, ReiHashimoto commented on docs/modules/studio.app.common.core.auth.rst
> +studio.app.common.core.auth package
`make docs`で呼び出している`sphinx-apidoc -f --no-toc -o ./docs/modules ./studio`
がこれらのファイルを自動生成するためのスクリプトです。

2023-11-06 07:13 UTC, itutu-tienday commented on studio/app/common/routers/algolist.py
> +    def get_nest_dict(cls, parent_value, parent_key: str) -> AlgoList:
了解しました。
※なお補足ですが、params 系のフリーズは、develop-main では生じていないように見えています。

2023-11-06 07:13 UTC, ReiHashimoto commented on studio/app/optinist/wrappers/caiman/cnmf.py
>  from studio.app.optinist.dataclass import CaimanCnmfData, FluoData, IscellData, RoiData
この辺りは決めの問題になってくると思いますが、その方針でOKかと思います。

2023-11-07 02:27 UTC, ReiHashimoto commented on studio/app/common/core/wrapper/wrapper.py
> +class Wrapper:
Algorithmにしましょうか。
あるいはAlgorithmNodeなど？

2023-11-07 04:13 UTC, ReiHashimoto commented on studio/app/common/core/wrapper/wrapper.py
> +class Wrapper:
abstract化を行いました。

2023-11-07 04:13 UTC, ReiHashimoto commented on studio/app/common/core/wrapper/wrapper_utils.py
> +            return wrapper_dict[name]["function"]
定数で定義するようにしました。

2023-11-07 04:15 UTC, ReiHashimoto commented
@itutu-tienday 
> 上記を試してみたところ、こちらの環境で以下のようなエラーが出ていますが、動作はしますでしょうか？

shpinxのversionの問題で、styleが読み込めていなかったようです。
（リリース時に問題はなかったのですが...）
versionを下げて対応しましたので、再度お試しください。

2023-11-07 04:23 UTC, itutu-tienday commented on studio/app/common/core/wrapper/wrapper.py
> +class Wrapper:
長いですが、機能の意味合いとしては、AlgorithmNodeTemplate かもしれないですね。
→ 縮めて、AlgorithmTemplate や NodeTemplate などでしょうか。
※ abstract class にすると より明確かと思います。

なお以下のページで、wrapper とつくキーワードが複数登場していました。
可能であれば、当初のキーワード（wrapper）の命名意図を確認できるとよさそう とも思います。
- https://github.com/oist/optinist/wiki/%E3%82%A2%E3%83%AB%E3%82%B4%E3%83%AA%E3%82%BA%E3%83%A0%E8%BF%BD%E5%8A%A0%E6%89%8B%E9%A0%86%E6%9B%B8data_wrapper
  - → data_wrapper, original_wrapper, など（おそらく現在のコードには存在はしていないが）

2023-11-07 04:24 UTC, ReiHashimoto commented on studio/app/optinist/wrappers/caiman/cnmf.py
>  from studio.app.optinist.dataclass import CaimanCnmfData, FluoData, IscellData, RoiData
一旦Wrapperを継承したクラスのメソッドとして実装してみましたが、イメージあっていますでしょうか？

2023-11-07 08:56 UTC, itutu-tienday commented on studio/app/common/core/wrapper/wrapper.py
> +class Wrapper:
確認しました。

※以下のプロパティもabstract（getter）化しても良いかと思いましたが、python ということで そこまでは不要か、と考えます。

```
    _INPUT_NODES: List[Param] = []
    _OUTPUT_NODES: List[Param] = []
    _DEFAULT_PARAMS: List[Param] = []
```

2023-11-07 09:14 UTC, itutu-tienday commented on studio/app/optinist/wrappers/caiman/cnmf.py
>  from studio.app.optinist.dataclass import CaimanCnmfData, FluoData, IscellData, RoiData
（レスポンスが遅くなりすみません）

指摘への修正イメージはあっています。

一点細かい点ですが、対象の関数 get_roi は class CaimanCnmf の状態に依存していないので（単なる共通関数）、class method（self未使用）で良さそうかと思いました。

2023-11-07 09:18 UTC, itutu-tienday commented on studio/app/common/core/experiment/experiment.py
> +    nwb: Dict[str, Union[ParamChild, ParamParent]]
一旦ベターな案はこちらもないので、ひとまずこの構成としましょうか。
※別件の API docs フリーズ への対処の際などに、再調査するなどで。

2023-11-08 01:17 UTC, ReiHashimoto commented on studio/app/optinist/wrappers/caiman/cnmf.py
>  from studio.app.optinist.dataclass import CaimanCnmfData, FluoData, IscellData, RoiData
classmethodに修正しました

2023-11-08 01:26 UTC, ReiHashimoto commented on studio/app/common/core/wrapper/wrapper.py
> +class Wrapper:
NodeTemplateだとInputなどのdataノードと混在しそうなため、AlgorithmTemplateが良さそうです。
やや長いので、AlgoTemplateとしました。

2023-11-09 05:32 UTC, itutu-tienday commented on studio/app/common/core/wrapper/wrapper.py
> +class Wrapper:
内容OKと思います

2023-11-13 02:16 UTC, ReiHashimoto commented on studio/app/common/routers/algolist.py
> +    def get_nest_dict(cls, parent_value, parent_key: str) -> AlgoList:
fastapiのバージョンアップによって解消しました。
最新のdevelop-mainをmergeしたため当PRでも解消済です。

2023-11-13 07:36 UTC, itutu-tienday commented on studio/app/common/routers/algolist.py
> +    def get_nest_dict(cls, parent_value, parent_key: str) -> AlgoList:
こちらでも最新版で事象は生じていないようであることを確認しました。

2023-11-13 07:45 UTC, itutu-tienday commented
@ReiHashimoto 
> shpinxのversionの問題で、styleが読み込めていなかったようです。

`make docs` のエラーの件ですが、現在の最新版でも、同じエラーが発生している模様です。
→こちらの環境では、sphinx-apidoc のコマンドが見つからない様なのですが、そのあたりが要因でしょうか？（`pip install -e '.[doc]'` は実施済）

2023-11-13 08:20 UTC, ReiHashimoto commented
@itutu-tienday 
> `make docs` のエラーの件ですが、現在の最新版でも、同じエラーが発生している模様です。 →こちらの環境では、sphinx-apidoc のコマンドが見つからない様なのですが、そのあたりが要因でしょうか？（`pip install -e '.[doc]'` は実施済）

poetry導入のPRをマージ済なので、`poetry install --with doc --no-root`を試していただけますか？
その後に`poetry show --only doc`で`sphinxcontrib-apidoc`がインストール済(パッケージ名が青色)であれば`sphinx-apidoc`コマンドは通るかと思います。

2023-11-13 08:27 UTC, ReiHashimoto commented
他のアルゴリズムへの適用中に以下の課題が発覚
対応方針検討中

- 異なるセクションでパラメータ名が重複するケースがある
  - docvalでは変数をフラットに受け取るため、セクションが別れていても変数名が重複すると受け入れ不可
  - 対象
    - lccd_cell_detection
      - min_area, max_area, sparseがblob_detector, roi_integrationのセクションで重複
    - svm
      - C, kernel, degree, gamma, coef0, shirinking, tol, decision_function_shapeがgrid_search.param_grid, SVCのセクションで重複
    - granger
      - maxlag, autolagがadfuller, cointのセクションで重複

2023-11-13 08:36 UTC, itutu-tienday commented
> poetry導入のPRをマージ済なので、

poetry の環境で、make docs が実行できることを確認しました。
※なお pip install 環境でも、sphinxcontrib-apidoc は導入されていましたが、コマンドにパスが通されていなかったようです（？）

ただし、その後以下のようなエラーが出ています。 （結果的にHTMLが生成されていない模様）
※現状は優先ではありませんので、また都合の良いタイミングでご確認いただければと思います。

```
$ make docs
〜〜 中略 〜〜
Theme error:
An error happened in rendering the page gui/index.
Reason: UndefinedError("'style' is undefined")
```

2023-11-13 08:57 UTC, ReiHashimoto commented
@itutu-tienday 

> poetry の環境で、make docs が実行できることを確認しました。 ※なお pip install 環境でも、sphinxcontrib-apidoc は導入されていましたが、コマンドにパスが通されていなかったようです（？）
> 
> ただし、その後以下のようなエラーが出ています。 （結果的にHTMLが生成されていない模様） ※現状は優先ではありませんので、また都合の良いタイミングでご確認いただければと思います。
> 
> ```
> $ make docs
> 〜〜 中略 〜〜
> Theme error:
> An error happened in rendering the page gui/index.
> Reason: UndefinedError("'style' is undefined")
> ```

ご確認ありがとうございます。こちらが以下のコメントで話題にしていた内容なのですが、再度調査したところ、問題はsphinx-rtd-themeのバージョンが古いことでした。
> shpinxのversionの問題で、styleが読み込めていなかったようです。
（リリース時に問題はなかったのですが...）
versionを下げて対応しましたので、再度お試しください。

こちらについては、https://github.com/arayabrain/barebone-studio/pull/152 で対応しているので、こちらのPR mergeで解消はします。
取り急ぎそれまでの確認にあたっては
```
poetry update --only doc sphinx-rtd-theme
```
でバージョンを更新できるはずです。

2023-11-14 00:26 UTC, itutu-tienday commented
> poetry update --only doc sphinx-rtd-theme

上記で、HTMLのbuild に成功したようです。フォローありがとうございます。

2023-12-11 02:14 UTC, ReiHashimoto commented
#232 での実装となるため、こちらはclose

2023-12-11 02:14 UTC, closed without merging