Replace setuptools to poetry
arayabrain/barebone-studio pull request #132
Opened 2023-11-03 03:13 UTC by quanpython

2023-11-06 01:54 UTC, ReiHashimoto requested changes
In my environment, I get following warning message.
(After updating poetry.lock by `poetry lock --no-update`, the message disappear in my env.)

```
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.
Path /private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_6cp367xbh2/croot/python-build_1679596513195/work for build does not exist
```

And more, there is a following error.
```
Installing ruamel-yaml (0.18.4): Failed

  RuntimeError

  Unable to find installation candidates for ruamel-yaml (0.18.4)
```

Do these reproduce in your environment?
If so, I hope them to be fixed.

2023-11-06 03:49 UTC, quanpython commented
@ReiHashimoto
I updated the `poetry.lock` file and specify version of `ruamel.yaml`. It seems the error has been resolved.
Please check it  again.

2023-11-06 12:17 UTC, ReiHashimoto requested changes

2023-11-07 01:02 UTC, ReiHashimoto approved these changes

2023-11-08 07:50 UTC, ReiHashimoto commented
@quanpython 
I made following changes by myself.

- `sphinx-pyproject` can only parse `[project]` but `[tool.poetry]` in pyproject.toml. -> I decided not to use this package.
- `sphinx_rtd_theme` has problem with version -> update lock file.

2023-11-10 01:05 UTC, merged