create Inscopix isxd reader module
arayabrain/barebone-studio pull request #257
Opened 2023-12-26 08:58 UTC by itutu-tienday

- PR内容
  - Inscopix isxd Readerモジュール作成

- 動作確認手順
  - Inscopix環境の構築
    1. Inscopixパッケージをインストール
    2. Python API 環境をセットアップ
        - conda creae env でのセットアップ
        - 具体的な手順はマニュアルを参考

  - データの配置
    - 以下テスト用データのローカル環境配置（任意のパス）
      - https://drive.google.com/drive/folders/1TOlkOHxMOm7lfJLVYG5w96Ju3KfGUc3N

  - テストコード（test_IsxdReader.py）を pytest で実行可能
    - テストコード内の設定（TEST_DATA_PATH）で、上で配置した テスト用データ, の格納パスを指定
    - テストコードは Linux/Windows の両環境で動作可能

- レビュー観点
  - レビュー観点
    - 動作や構成が妥当であるか
    - 取得画像データのWorkfllow Nodeへの投入検証

- 想定課題
  - Inscopix導入手順・環境構成をどうするか
    - 利用には Inscopix 本体のインストールや、conda create env が必要
    - optinist や snakemake とどの様に協働させるか、要設計
    - 確認している注意点
      - `conda init bash` を行うと、glibc等のパスが変化し、他のReader(Nikon, Olympus)のDLLが動作しないケースがある (問題ないケースもある？)
      - Inscopix APIのPython利用バージョンは、3.10 (optinistのpythonバージョンと異なる)

2023-12-26 10:29 UTC, ReiHashimoto commented
ひとまずこちらの環境でも対象のテストをdocker execから実行できることまで確認済みです。

```
(isxenv) root@35d313a57984:/app# pytest -s /app/studio/app/optinist/microscopes/test_IsxdReader.py
======================================================================= test session starts ========================================================================
platform linux -- Python 3.10.13, pytest-7.4.3, pluggy-1.3.0
rootdir: /app
configfile: pyproject.toml
plugins: env-1.1.1, anyio-3.7.1
collected 1 item                                                                                                                                                   

studio/app/optinist/microscopes/test_IsxdReader.py ('{"data_name": "fixed-oist-sample_data_short.isxd", "spacing": {"width": 800, '
 '"height": 1280}, "timing": {"start": "2018-07-19 13:36:04", "period_msec": '
 '50, "num_samples": 450, "dropped": [], "cropped": [], "blank": []}}')
OMEDataModel(image_name='fixed-oist-sample_data_short.isxd',
             size_x=800,
             size_y=1280,
             size_t=450,
             size_c=0,
             fps=20.0)
'null'
.
```

## 課題

- Python実行環境の差異
  - Algorithmノードであればsnakemakeによって異なるconda環境を立ち上げが可能だが、データノードのためどうするか
    - (案1) suite2p_file_convertのように、isxd変換用のノードを挟む
      - この場合、snakemakeからInscopixの`environment.yml`に含まれる`pip install -e .`が通るか要検証
    - (案2) 別アプリケーションとしてinscopixのAPIを実行するためのFastAPIアプリケーションを立ててしまう
    - (案3) OptiNiStのpython versionを3.10に上げてしまう
      - どうせ上げるならば最新版にしたい、かつこのライブラリによってバージョンロックされてしまうので、あまり望ましい対応ではない

2023-12-26 10:34 UTC, ReiHashimoto requested changes
構成等は妥当かと思います。
環境構築が課題ですね。こちらでも検証等してみます。

2023-12-26 10:34 UTC, ReiHashimoto commented on studio/app/optinist/microscopes/IsxdReader.py
> +            image_frames.append(movie.get_frame_data(i))
細かいですが、パフォーマンスを少しでも上げるため、リスト内包表記にしていただくと良いと思います。

2023-12-27 08:30 UTC, itutu-tienday commented
> Algorithmノードであればsnakemakeによって異なるconda環境を立ち上げが可能だが、データノードのためどうするか

以下の案も検討できるかもしれません。

- (案4) 事前にInscopix用のconda環境（isxenv）をユーザー側でセットアップしておく
  - どのタイミングで対象のconda環境へ切り替えるかは、要設計
  - 固有カスタマイズとなるが、Data Node内の処理で切り替えるのが、ユーザビリティ的にはよさそうか？

2023-12-28 08:31 UTC, itutu-tienday commented on studio/app/optinist/microscopes/IsxdReader.py
> +            image_frames.append(movie.get_frame_data(i))
@ReiHashimoto 
リスト内包表記へ修正しました。

2024-01-09 00:12 UTC, merged