Roi time series select colour change
arayabrain/barebone-studio pull request #402
Opened 2024-08-05 05:45 UTC by milesAraya

[Issue 359](https://github.com/arayabrain/barebone-studio/issues/359)の解決です。

ROI が選択されると色が白に変わり、Fluorescence plotがリンクされていればtime seriesがプロットされます。
Legend ROI が選択されると ROI は白くなります。 
ROI を選択解除にするとtime seriesは消えます。Legend ROIを選択解除すると ROI は通常の色に戻ります。

既存の temp_merge_roi フレームワークと同様に temp_selected_roi を使用することで実現。

When ROI are selected, they change colour to white, and if fluorescence window is linked time-series is plotted.
When the legend ROI is selected the ROI turns white.  
When ROI unselected the time series disappears. When the legend is unselected the ROI returns to normal colour. 

Achieved through using a temp_selected_roi, similar to the existing temp_merge_roi framework.

2024-08-20 05:11 UTC, milesAraya commented
test case:
https://docs.google.com/spreadsheets/d/127u9f5e1jLAPJRP7iXA0cZMVwpZk6MqW/edit?usp=sharing&ouid=110721479235758822364&rtpof=true&sd=true

2025-01-06 05:08 UTC, itutu-tienday requested changes

2025-01-06 05:08 UTC, itutu-tienday commented on frontend/src/components/Workspace/Visualize/Editor/TimeSeriesItemEditor.tsx
> +    dispatch(
- Behavior before Edit Roi is started
  - Flou selected before start of Edit Roi is not released after start of Edit Roi.
    -> The selection of ROI in Edit Roi and the selection of Flou do not match.
    -> When Flou is selected in this state, the ROI selection is canceled, which seems to be a reversed operation.

2025-01-06 05:08 UTC, itutu-tienday commented on frontend/src/components/Workspace/Visualize/Editor/TimeSeriesItemEditor.tsx
> +    dispatch(
- Bug
  - React error when Add Roi -> Commit -> Select the added ROI?

2025-03-11 01:29 UTC, milesAraya commented on frontend/src/components/Workspace/Visualize/Plot/ImagePlot.tsx
> +        temp_merge_roi: [],
When merging or deleting, all the ROIs turn orange or purple before selection. Actually, when turning on Merge, the ROI should have their normal colour, then only after selection to turn orange or purple.

2025-03-11 01:29 UTC, milesAraya commented on frontend/src/components/Workspace/Visualize/Plot/ImagePlot.tsx
> +      }
When ROI are selected for merge, they change to purple. But after you click OK, the special Edit colour-change disappears and the ROI have their normal colours again. The two merged ROI should have the special colour until after Commit Edit.

2025-03-14 07:29 UTC, tsuchiyama-araya commented
@sanglevinh 
I checked it and noticed that the color of ROI and Fluo is different can you add a fix for this? Thank you.
![Screenshot 2025-03-14 162247](https://github.com/user-attachments/assets/eeeecaac-aef3-428c-8826-552e66969e52)

2025-03-14 07:41 UTC, sanglevinh commented
> @sanglevinh I checked it and noticed that the color of ROI and Fluo is different can you add a fix for this? Thank you. ![Screenshot 2025-03-14 162247](https://private-user-images.githubusercontent.com/169987401/422684920-eeeecaac-aef3-428c-8826-552e66969e52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE5Mzc4NDAsIm5iZiI6MTc0MTkzNzU0MCwicGF0aCI6Ii8xNjk5ODc0MDEvNDIyNjg0OTIwLWVlZWVjYWFjLWFlZjMtNDI4Yy04ODI2LTU1MmU2Njk2OWU1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMxNFQwNzMyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjYwOTAzNDdjMjA0NTg4NDc3Nzk3NWZlYWY3NmY0OTZlMTc2Y2EwOWQ1NTFjNGI2ZGIwYTgxODgzNTAwNzU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WgvmQhJHJHYz0DKLk6ROpIMBc29HZqRd1tZpF0qHK3w)

@tsuchiyama-araya Currently, I am using the react-plotlyjs-ts library, and the way of setting colors for the two charts is different, so making the colors of both charts match could take a lot of time. I remember you mentioned creating a task for this issue, but it was later paused and replaced with another task.

2025-03-14 07:44 UTC, sanglevinh commented on frontend/src/components/Workspace/Visualize/Editor/TimeSeriesItemEditor.tsx
> +    dispatch(
@itutu-tienday  When adding an ROI, it's just temporary data, and the API for getting fluorescence will encounter an error. Therefore, for the time being, I will not allow this API to be called when adding an ROI

2025-03-14 07:45 UTC, sanglevinh commented on frontend/src/components/Workspace/Visualize/Editor/TimeSeriesItemEditor.tsx
> +    dispatch(
@itutu-tienday It seems like it has been fixed

2025-03-14 08:43 UTC, itutu-tienday approved these changes

2025-03-14 08:44 UTC, tsuchiyama-araya commented
@sanglevinh 
Oh sorry, yes i remember talking about that before now. We will check it here and fix. Thank you for answering

2025-03-14 08:44 UTC, merged