Workflowのexport/import機能
arayabrain/barebone-studio pull request #41
Opened 2023-08-16 01:47 UTC by ReiHashimoto

### experiment.yamlの分離

従来のexperiment.yamlを以下の2つに分離
- experiment.yaml: 解析のメタデータ
  - 名前、ID
  - 結果
  - etc...
- workflow.yaml: GUIでのノード表示に必要な情報
  - nodeDict
  - edgeDict

### workflow.yamlのエクスポート

Records画面からworkflow.yamlをダウンロード可能にした

![Screenshot 2023-08-16 at 10 02 42](https://github.com/arayabrain/barebone-studio/assets/42664619/b782da3f-1fbe-4c9a-9f19-f3b06f6c6f08)

- /workflow/download/{workspace_id}/{unique_id}のAPIで取得

### workflow.yamlのインポート

Workflow画面のLOADボタンからworkflow.yamlをインポートし、ノードの復元を可能にした

![Screenshot 2023-08-16 at 10 02 58](https://github.com/arayabrain/barebone-studio/assets/42664619/f4703302-2291-452a-a2e6-03ae80b4f555)

- /workflow/loadエンドポイントへのAPIを通してyamlファイルをパース
  - ロードしたyamlファイルは保存されない
- LOADの際には、inputノードのパスは復元しない

### その他
- 従来のexperiments/importをworkspace/importに修正
  - 元々nodeDict, edgeDictしか返さないAPIのため

2023-08-16 01:50 UTC, ReiHashimoto commented
flake8のCIがFailしていますが、
flake8の最新バージョンが6.0.0から6.1.0になり、E721のチェックで弾かれるようになったためです。

#40 で修正しているので、そちらのマージ後rebaseすれば解消します。

2023-08-17 07:54 UTC, itutu-tienday requested changes

2023-08-17 07:54 UTC, itutu-tienday commented on studio/app/common/routers/workflow.py
> +    return FileResponse(config_filepath, filename=DIRPATH.WORKFLOW_YML)
@ReiHashimoto 
ここで対象ファイル（workflow.yaml）が存在しない場合（通常発生はしないケース）、`Unhandled Rejection (Error): Download Error` が発生するようです。（画面にはエラーが表示され復帰不可となる）

念のため、ファイル存在チェックを入れておくとよいかと思います。
※他の類似箇所（ダウロード関係API）も同様かもしれませんが、ひとまずコメントします。

2023-08-17 07:54 UTC, itutu-tienday commented on studio/app/common/routers/workflow.py
> +@router.post("/load")
@ReiHashimoto 
現状、workflowの復元周りの処理に、複数のキーワードが用いられている様です。
・import … 既存のAPIのI/F
・reproduce … 画面上の表記
・load … 今回追加のAPIのI/F

画面上の表記は、もしかするとユーザー要望で定められた経緯かもしれませんが、
reproduce と load は動作的には ほぼ同様の処理と思いますので、用語を寄せておく形がよいかもしれません。

一旦コメントでまですが、ご意見あればお願いします。

2023-08-17 08:30 UTC, ReiHashimoto commented on studio/app/common/routers/workflow.py
> +@router.post("/load")
@itutu-tienday 
そうですね、確かに寄せた方が良さそうです。
- 既存の/import APIエンドポイントを/reproduceにする
- 新規のloadを/importにする

上記方針に合わせ、各種変数名などもfix

この対応でいかがでしょうか?

2023-08-17 10:24 UTC, itutu-tienday commented on studio/app/common/routers/workflow.py
> +@router.post("/load")
@ReiHashimoto 
上記の内容で、OKかと思います（変更箇所は量があるかもしれませんが…）
※画面上の表記も Load→Import にするという形ですね

2023-08-17 11:48 UTC, ReiHashimoto commented on studio/app/common/routers/workflow.py
> +    return FileResponse(config_filepath, filename=DIRPATH.WORKFLOW_YML)
@itutu-tienday 
ありがとうございます
FileResponse系のAPIでのエラーハンドリングを修正しました。
また、フロントでもthrow Errorだけだったので、snackbarでのメッセージ表示によるハンドリングを行いました。

2023-08-18 05:04 UTC, itutu-tienday requested changes
@ReiHashimoto 
今少し、指摘を追記しています。ご確認ください。

2023-08-18 05:04 UTC, itutu-tienday commented on frontend/src/components/Workspace/Experiment/Button/DownloadButton.tsx
> +      <a href={url} download={`workflow.yaml`} className="hidden" ref={ref}>
@ReiHashimoto 
ダウンロードファイル名には、workflow_id(uid) を付与しておいてもよいかもしれません。（`workflow_${uid}.yaml` など)

※Records画面から、複数の Workflow File を順次ダウンロードする利用ケースを想定して。

2023-08-18 06:49 UTC, ReiHashimoto commented on frontend/src/components/Workspace/Experiment/ExperimentTable.tsx
> +          <TableCell>Workflow</TableCell>
@itutu-tienday 
適用してみるとこのようになります。
表記的にはわかりやすいのですが、コンパクトな方がベターかなという印象です。

![Screenshot 2023-08-18 at 15 42 03](https://github.com/arayabrain/barebone-studio/assets/42664619/a560f7dd-dd19-49be-96b1-616affb6ad12)

この辺りはドキュメントに頼っていくか、
以下のようにアイコンを変えてみることでファイルであることを強調する、などのアプローチもあると思います。

![Screenshot 2023-08-18 at 15 48 32](https://github.com/arayabrain/barebone-studio/assets/42664619/0a05e924-9cf1-44ca-8e1b-d00c6563cd4a)

2023-08-18 06:51 UTC, ReiHashimoto commented on frontend/src/components/Workspace/Experiment/Button/DownloadButton.tsx
> +      <a href={url} download={`workflow.yaml`} className="hidden" ref={ref}>
nwb, workflow, snakemakeのダウンロードファイルの名称を{種類}_{workspace_id}の形式に統一しました。

2023-08-18 06:54 UTC, ReiHashimoto commented on frontend/src/components/Workspace/Experiment/ExperimentTable.tsx
> +          <TableCell>Workflow</TableCell>
補足：muiのアイコンはこちらです。

https://mui.com/material-ui/material-icons/
上の図では
SimCardDownloadOutlined
を使用しました。

2023-08-18 08:26 UTC, itutu-tienday commented on frontend/src/components/Workspace/Experiment/ExperimentTable.tsx
> +          <TableCell>Workflow</TableCell>
@ReiHashimoto 
そうですね、ラベルは簡潔に現状の形式としましょう。

またアイコンは、ご提示のものが、より分かりやすい様に思いました。
よろしければ、アイコンはアップデートしましょうか。

2023-08-18 08:33 UTC, ReiHashimoto commented on frontend/src/components/Workspace/Experiment/ExperimentTable.tsx
> +          <TableCell>Workflow</TableCell>
以下の対応を行いました！

- アイコンの変更
- SnakeFile→Snakemakeに表記の変更

2023-08-18 08:46 UTC, itutu-tienday approved these changes

2023-08-18 08:50 UTC, merged