Setting Test Environment for Jest Test
arayabrain/barebone-studio pull request #426
Opened 2024-09-02 05:10 UTC by tsuchiyama-araya

#403 Implemented.

Package JSON file was updated to be able to use jest.

2024-09-02 09:54 UTC, itutu-tienday requested changes

2024-09-02 09:54 UTC, itutu-tienday commented on frontend/package.json
>    "jest": {
#426 で記載されている以下の事項は、対応済みでしょうか
> - 新しいテストにWarningやエラーの線が出ないこと

2024-09-02 10:47 UTC, tsuchiyama-araya commented on frontend/package.json
>    "jest": {
エラーについてはすでに対応済みです。
Warningについてですが、toBeInTheDocument() 関数が expect をインポートしても使用できなくなっています。
考えられる理由として、@jest/globals からインポートしてみたところ、別の場所からインポートされている expect が使用されている可能性があります。

そのため、インポートが行われていないことで、警告が表示されているのだと思います。
これを一時的に回避するために、先頭に /* eslint-disable no-undef */ を追加しました。
この方法は理想的ではありませんが、現状はこの対応で進めています。

もしこの方法は問題であれば、別のアプローチで修正を行います。

2024-09-03 03:57 UTC, tsuchiyama-araya commented on frontend/package.json
>    "jest": {
補足です。

こちらChat GPTでどうやって、Expectだけをjest-domから使うかを質問しました。
https://chatgpt.com/share/95c86654-2ebd-46b7-8c3a-effdc0450eff

こちらは、SetUpファイルに設定することを指示されましたが、こちらはもうすでに実施済みです。

2024-09-10 03:35 UTC, itutu-tienday commented on frontend/package.json
>    "jest": {
テストコード中、警告は抑制されているようであることを確認。

2024-09-10 03:35 UTC, itutu-tienday commented on frontend/package.json
>      "react-app-rewired": "^2.2.1",
以下の修正はこちらに取り込んでおくとよいでしょうか？ ご確認ください。
- 53b4a41

2024-09-10 07:33 UTC, tsuchiyama-araya commented on frontend/package.json
>      "react-app-rewired": "^2.2.1",
向き先をdevelop-testに２つのブランチを向かせますが、一応対応した方がいいですか？

2024-09-10 12:09 UTC, itutu-tienday approved these changes

2024-09-10 23:53 UTC, merged