Feature 443 Create multiple frontend test
arayabrain/barebone-studio pull request #451
Opened 2024-10-01 08:01 UTC by tsuchiyama-araya

【内容】
とりあえず複数のフロントエンドテストを作成することを目標としています。
エラーなどがあれば、記載すること。記載箇所は下記のスプレッドシートにしました。

スプレッドシート：
https://docs.google.com/spreadsheets/d/1WdtZA0jXOrPrVQmtkEGkzk9erUV-aMRTgGA1cT7G7N4/edit?gid=61555119#gid=61555119

2024-10-17 08:39 UTC, itutu-tienday requested changes

2024-10-17 08:39 UTC, itutu-tienday commented on frontend/src/components/Workspace/__tests__/Experiment/NWBDownload.test.tsx
> +      expect(downloadExperimentNwbApi).toHaveBeenCalledWith(1, "exp1", "node1")
ここは、APIのresponseはチェックしていますか？
- 応答コード
- response body (ダウンロードされたファイル)
  - ※実際のダウンロードまで検証すべき？ ベストプラクティスはどうか？

2024-10-17 08:39 UTC, itutu-tienday commented on frontend/src/components/common/ConfirmDialog.tsx
> +  const dataTestId = confirmLabel
(この箇所への指摘ではないが、共通コメントとしてここに記載)
- テスト対象一覧に、以下の情報を追記してください
  - https://docs.google.com/spreadsheets/d/1WdtZA0jXOrPrVQmtkEGkzk9erUV-aMRTgGA1cT7G7N4/edit?gid=61555119#gid=61555119
  - [ ] 各テスト項目に紐づく、テストファイルのパスを記載してください
  - [ ] `HAS ERROR` の内容を記載してください（内容、想定対策）
  - [ ] シート `Visualize` の項目も、`HAS ERROR` なのでは？

2024-10-18 08:27 UTC, tsuchiyama-araya commented on frontend/src/components/Workspace/__tests__/Experiment/NWBDownload.test.tsx
> +      expect(downloadExperimentNwbApi).toHaveBeenCalledWith(1, "exp1", "node1")
ありがとうございます。
確かに、結果はチェックされていないです。

あくまで、APIが呼び出されていることのチェックをしています。
レスポンスのテストを実装できるかを確認してみます。

2024-11-06 07:21 UTC, itutu-tienday commented on frontend/src/components/common/ConfirmDialog.tsx
> +  const dataTestId = confirmLabel
(この箇所への指摘ではないが、共通コメントとしてここに記載)

- ドキュメントを修正ください。（各ドキュメント内にコメント記載）
  - [ ] https://docs.google.com/document/d/1RZ-xgzZhjqAmPEA_rJ1RrVIMK2nf93BAs6Ene0rIw-0/edit?tab=t.0

2024-11-11 01:45 UTC, tsuchiyama-araya reviewed
コメントに追加しました。
確認お願いします。

2024-11-11 02:57 UTC, itutu-tienday commented on frontend/src/components/Workspace/__tests__/Experiment/NWBDownload.test.tsx
> +      expect(downloadExperimentNwbApi).toHaveBeenCalledWith(1, "exp1", "node1")
対象のAPI `downloadExperimentNwbApi` は、ファイルダウンロードのAPIのため、現在の構成（Responseの内容詳細は検査対象外）でもOKそうですね。

ダウンロード以外の ResponseがJSON形式のAPIについては、Response内容の検査は、必要だろうと思われます。

ここの comment は、resolve としておきます。

2024-11-19 09:29 UTC, itutu-tienday approved these changes

2024-11-19 10:13 UTC, merged