登録済みInput画像データのUIからの削除機能
arayabrain/barebone-studio pull request #481
Opened 2024-11-11 05:46 UTC by tsuchiyama-araya

**Content**

現在(optinist v1.1)、登録済みInput画像データのUIからの削除機能がない（登録のみ可）。削除機能はあるとよいと想定される。
Tasks

**Others**

既存WFのInputノードに指定されている画像データが、ファイルシステムに実際に存在していない場合（手動で削除された場合など）、WFの実行エラーとなる。またUIから上記の画像情報の削除も行えない。（Inputノードの削除→配置を要する）

2024-11-18 00:25 UTC, itutu-tienday commented
以下、PRをメンテナンスください
- Testcaseの情報を、PRに記載しておいてください
- PRをissueとリンクしておいてください

2024-11-18 00:29 UTC, tsuchiyama-araya commented
今回の件のテストケースです。
https://docs.google.com/spreadsheets/d/1vCaMO75yQrbGvOhHYnhKasqbmQhVDGyy/edit?gid=854497464#gid=854497464

2024-11-18 02:14 UTC, itutu-tienday requested changes

2024-11-18 03:15 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/Dialog/FileSelectDialog.tsx
> +        <FilePathSelectedListView
選択中ファイルが0件の場合、メッセージ表示などあると良さそうです。
→ 「No file selected」など

2024-11-19 02:03 UTC, tsuchiyama-araya commented on studio/app/common/routers/files.py
> +    except FileNotFoundError:
承知しました。
他のエラーハンドリングも追加します。

2024-11-19 02:08 UTC, tsuchiyama-araya commented on frontend/src/components/Workspace/FlowChart/Dialog/FileSelectDialog.tsx
> +        <FilePathSelectedListView
こちらは、対応してあります。
<img width="486" alt="Screenshot 2024-11-19 at 11 04 41" src="https://github.com/user-attachments/assets/6122ca49-5716-4630-be31-51d7553ef52b">

2024-11-19 02:08 UTC, tsuchiyama-araya commented on frontend/src/components/Workspace/FlowChart/Dialog/FileSelectDialog.tsx
> +          <DeleteIcon />
ありがとうございます。
こちらは、他のデザインと同じにします。

デザインとしては、赤色ですね。そして、無効化になっている場合はGrayになります。

2024-11-19 02:55 UTC, itutu-tienday commented on frontend/src/api/files/Files.ts
> +export async function deleteFileTreeApi(
"deleteFileTree" の場合、文字通り FileTree の削除（複数ファイルの削除）の意味として伝わりそうです。
ファイル単体に対する操作であれば、"deleteFile" が適切でしょう。

2024-11-19 10:14 UTC, tsuchiyama-araya commented on frontend/src/api/files/Files.ts
> +export async function deleteFileTreeApi(
承知しました。対応します。

2024-11-21 05:10 UTC, itutu-tienday requested changes

2024-11-21 05:10 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/Dialog/FileSelectDialog.tsx
> +        <Button
delete iconが無効化されている状態でも、クリック可能（削除操作可能）とはなっていないか？
※上記のパターンは、Testcaseには記載されているか？

2024-11-21 05:10 UTC, itutu-tienday commented on studio/app/common/routers/files.py
> +    except FileNotFoundError:
- すべてのエラーがcatch(except)されていません。
  - 基底の `Exception` が発生した場合、catchされない模様。
- またexcept の指定がやや細かいため、コードの保守面から、「主要なもの(FileNotFoundError ?)」とその他「Exception」の2パターン程度でよいものと思われます。

2024-11-21 08:47 UTC, itutu-tienday requested changes

2024-11-22 03:34 UTC, tsuchiyama-araya commented on studio/app/common/routers/files.py
> +        os.remove(filepath)
指摘ありがとうございます。
こちらは対応しましたので、お手数ですが、再度ご確認お願い致します。

2024-11-25 03:50 UTC, itutu-tienday requested changes

2024-11-25 03:50 UTC, itutu-tienday commented on studio/app/common/routers/files.py
> +        DOWNLOAD_STATUS.pop(filepath, None)
質問となりますが、
既存のコードでは、`DOWNLOAD_STATUS.pop` を行っている場所はないようですが、
- このコードを追加しない場合、どのような影響（問題）がありますでしょうか？
- 既存のコードで、`DOWNLOAD_STATUS.pop` が行われていないのは、問題はなさそうでしょうか？

2024-11-25 03:50 UTC, itutu-tienday commented on studio/app/common/routers/files.py
> +    except FileNotFoundError:
修正済みを確認

2024-11-25 03:50 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/Dialog/FileSelectDialog.tsx
> +        <Button
> delete iconが無効化されている状態でも、クリック可能（削除操作可能）とはなっていないか？

上記がまだ未対応の模様。 確認・対応いただければと思います

2024-11-25 03:50 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/Dialog/FileSelectDialog.test.tsx
> +import React from "react"
（このコード箇所への指摘ではないですが、）
以下のテストケースファイルへ、review commentを追記しています。確認と更新をお願いします。
https://docs.google.com/spreadsheets/d/1vCaMO75yQrbGvOhHYnhKasqbmQhVDGyy/edit?gid=854497464#gid=854497464

2024-11-28 00:12 UTC, tsuchiyama-araya commented on frontend/src/components/Workspace/FlowChart/Dialog/FileSelectDialog.test.tsx
> +import React from "react"
ありがとうございます。
こちらに関しては、修正しましたので、お手数ですが、ご確認いただけると幸いです。

2024-11-28 05:34 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/Dialog/FileSelectDialog.test.tsx
> +import React from "react"
> こちらに関しては、修正しましたので、

どの項目を修正されていますか？
※シート内に未解決の comment がまだ 5件ほど残っているようです。

2024-11-28 05:45 UTC, tsuchiyama-araya commented on frontend/src/components/Workspace/FlowChart/Dialog/FileSelectDialog.test.tsx
> +import React from "react"
オレンジ色になっている部分は、前回ご指摘いただいた箇所で、修正を反映した項目です。
また、残っていた5件のコメントについても対応しましたので、お手数ですがご確認いただけますと幸いです。

2024-11-28 05:54 UTC, tsuchiyama-araya commented on studio/app/common/routers/files.py
> +        DOWNLOAD_STATUS.pop(filepath, None)
ありがとうございます。
処理と見た目としては、影響はないと思います。
詳細はChat GPTさんに聞いてみましたので、参考にお願いします。
https://chatgpt.com/share/674804da-1c74-8013-b11f-32c0f4736acc

2024-11-28 06:05 UTC, itutu-tienday requested changes

2024-11-28 06:05 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/Dialog/FileSelectDialog.test.tsx
> +import React from "react"
テストケースのコメントへ追記していますが、以下のリンクの内容へ、対応いただければと思います
https://github.com/arayabrain/barebone-studio/pull/481/files#r1851360391

2024-11-28 06:56 UTC, tsuchiyama-araya commented on frontend/src/components/Workspace/FlowChart/Dialog/FileSelectDialog.test.tsx
> +import React from "react"
@itutu-tienday 
選択中の仕様を更新しました。
テストケースも更新しました。選択中のファイルのDelete Iconをクリックしても、何も起こらない仕様になっています。

お手数ですが、ご確認お願いします。

2024-11-28 07:14 UTC, itutu-tienday requested changes

2024-11-28 07:14 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/Dialog/FileSelectDialog.tsx
> +        <Button
細かいですが、delete button が disabled 時は、マウスカーソルも変えませんか？（簡易なら）

2024-11-28 07:14 UTC, itutu-tienday commented on studio/app/common/routers/files.py
> +        DOWNLOAD_STATUS.pop(filepath, None)
> 詳細はChat GPTさんに聞いてみましたので、参考にお願いします。

すみませんが、質問への回答としては情報不足のようです。（一般論を述べているようだが、 元の質問は、optinistの既存コードの仕様に関する質問）

2024-11-28 08:45 UTC, itutu-tienday commented on studio/app/common/routers/files.py
> +        DOWNLOAD_STATUS.pop(filepath, None)
- #489 で後続対応ということで、ここではクローズとなる

2024-11-28 08:49 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/Dialog/FileSelectDialog.tsx
> +            Are you sure you want to delete this item?
削除確認ダイアログで、削除対象のファイル名を、確認メッセージに含めていただけますか。
※Record画面のDelete の確認ダイアログを、参考ください。

2024-11-29 07:32 UTC, tsuchiyama-araya commented on frontend/src/components/Workspace/FlowChart/Dialog/FileSelectDialog.tsx
> +            Are you sure you want to delete this item?
こちら対応しました。
お手数ですが、ご確認お願い致します

2024-12-02 01:38 UTC, itutu-tienday requested changes

2024-12-02 01:38 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/Dialog/FileSelectDialog.tsx
> +            Are you sure you want to delete this item?
修正により、.tsx で警告が生じていませんか？

```
[eslint] 
src/components/Workspace/FlowChart/Dialog/FileSelectDialog.tsx
  Line 12:10:  'enqueueSnackbar' is defined but never used. Allowed unused vars must match /^_/u           @typescript-eslint/no-unused-vars
  Line 20:10:  'DialogContentText' is defined but never used. Allowed unused vars must match /^_/u         @typescript-eslint/no-unused-vars
  Line 63:6:   'DeleteConfirmDialogProps' is defined but never used. Allowed unused vars must match /^_/u  @typescript-eslint/no-unused-vars

```
確認と調整をお願いします

2024-12-03 02:21 UTC, itutu-tienday approved these changes

2024-12-03 03:09 UTC, merged