Workflow実行時のPipelineテスト
arayabrain/barebone-studio pull request #486
Opened 2024-11-21 01:53 UTC by tsuchiyama-araya

### 【問題】
ワークフロースクリーンのテストは、コンポーネント（React Flow）とJestの互換性の問題により、まだ実装されていません。

### 【解決策】
ワークフローの状態管理に焦点を当てたテストの実装
ワークフロースクリーンのテストで重要なポイントは、ワークフローの実行状態をテストすることです。そのため、Reactコンポーネントに依存しないテスト方法を検討します。

### 【実装】
Reduxの状態管理や非同期アクションの動作をモックデータを用いて詳細に検証しています。特に、非同期アクションが成功/失敗した場合の状態遷移や、各プロパティが期待通りの値を持つことを確認することに重点を置いています。

### 関連リンク
[Issue #443](https://github.com/arayabrain/barebone-studio/issues/443)
[Issue #302](https://github.com/arayabrain/barebone-studio/issues/302)

2024-11-21 05:58 UTC, itutu-tienday requested changes

2024-11-21 05:58 UTC, itutu-tienday commented on frontend/src/store/slice/Pipeline/Pipeline.test.ts
> +    requestId: "FmYmw6sCHA2Ll5JJfPuJN",
テスト用の requestId（同一値）は、定数化しておく形がよいように思います

2024-11-21 05:58 UTC, itutu-tienday commented on frontend/src/store/slice/Pipeline/Pipeline.test.ts
> +          status: "StartSuccess" as const,
statusの定義に PipelineType.ts の定数を使用していないのは、どのような意図からでしょうか？

2024-11-21 05:58 UTC, itutu-tienday commented on frontend/src/store/slice/Pipeline/Pipeline.test.ts
> +const createFulfilledAction = (
そもそもですが、このファイルのテストコードは、実際のコードのどの範囲をテスト（coverage）対象としたものでしょうか？

- 他の PilelineXXXX ファイルは、テストの対象外でしょうか？ （PipelineSlice.ts のみがテスト対象？）
- 上記が対象外の場合、その事由を確認させてください（文面では分かりづらそうなので、会話共有しましょう）

2024-11-22 08:52 UTC, tsuchiyama-araya commented on frontend/src/store/slice/Pipeline/Pipeline.test.ts
> +    requestId: "FmYmw6sCHA2Ll5JJfPuJN",
対応します。
ありがとうございます。

2024-11-22 08:52 UTC, tsuchiyama-araya commented on frontend/src/store/slice/Pipeline/Pipeline.test.ts
> +          status: "StartSuccess" as const,
ありがとうございます。
こちらも対応します。

2024-11-22 08:52 UTC, tsuchiyama-araya commented on frontend/src/store/slice/Pipeline/Pipeline.test.ts
> +const createFulfilledAction = (
こちらは資料でまとめますので、少々お待ちください。
完了したら、Slackの方で報告します。

2024-11-22 08:58 UTC, tsuchiyama-araya commented
@itutu-tienday 
ご確認いただきありがとうございます。
定数化できる箇所を修正いたしましたので、お手数ですがご確認いただけますと幸いです。

なお、テストのカバレッジについては現在資料を作成中ですので、少々お時間をいただければと思います。

2024-11-25 02:03 UTC, tsuchiyama-araya commented
今回のテストCoverageを資料に追加しました。
https://docs.google.com/spreadsheets/d/1WdtZA0jXOrPrVQmtkEGkzk9erUV-aMRTgGA1cT7G7N4/edit?gid=1127361346#gid=1127361346

また、Jest Coverageを追加しましたので、yarn test-coverage {filePath} を実行すれば、
全体のファイルのテストCoverageを確認できます。

お手数ですが、ご確認お願い致します。

2024-11-25 04:01 UTC, itutu-tienday requested changes

2024-11-25 08:28 UTC, tsuchiyama-araya commented on frontend/src/store/slice/Pipeline/Pipeline.test.ts
> +import { Edge } from "reactflow"
ありがとうございます。
こちら対応させていただきました。

お手数ですが、ご確認お願い致します。

2024-11-26 00:53 UTC, tsuchiyama-araya commented on frontend/src/store/slice/Pipeline/Pipeline.test.ts
> +const createFulfilledAction = (
こちらはPipeline Hooksにコメントを追加しましたが、
他の完全ではないファイルにもメモを記載した方が良いでしょうか？

2024-11-26 04:20 UTC, itutu-tienday requested changes

2024-11-26 04:20 UTC, itutu-tienday commented on frontend/src/store/slice/Pipeline/Pipeline.test.ts
> +  actionType: AsyncThunk<any, any, any>,
FulfilledAction のみ、type 指定に generics を利用しているのは、どのような事由からでしょうか？
※pending や reject では、generics を使用せず 個別に ActionClass が定義されているように見えています。

2024-11-28 00:58 UTC, tsuchiyama-araya commented on frontend/src/store/slice/Pipeline/Pipeline.test.ts
> +const createFulfilledAction = (
@itutu-tienday 
お疲れ様です。
解説を残しましたので、お手数ですが、ご確認お願いします。

2024-11-28 01:44 UTC, tsuchiyama-araya commented on frontend/src/store/slice/Pipeline/Pipeline.test.ts
> +  actionType: AsyncThunk<any, any, any>,
ご指摘ありがとうございます。
こちら対応しましたので、お手数ですが、再度ご確認お願い致します。

2024-11-28 05:51 UTC, itutu-tienday requested changes

2024-11-28 05:51 UTC, itutu-tienday commented on frontend/src/store/slice/Pipeline/Pipeline.test.ts
> +  actionType: AsyncThunk<any, any, any>,
上の修正内容について、

例えば、修正で追加された以下のクラスの組み合わせなどは、処理内容が同じで、かつ どちらも1箇所からのみの呼び出しであるようです。
- createRunResultFulfilledAction と createCancelFulfilledAction
- createRunResultRejectedAction と createCancelRejectedAction
- など

なお、createFulfilledAction などは、複数箇所（2箇所）から呼び出されているため、generics を利用している意図は理解できます。
上記のようなクラス（genericsを使用しているが、実質そのままコピーされており、genericsの効果がない）は、createFulfilledAction のように共通化可能ではないでしょうか？

2024-12-02 01:59 UTC, itutu-tienday requested changes

2024-12-02 01:59 UTC, itutu-tienday commented on frontend/src/store/slice/Pipeline/Pipeline.test.ts
> +const pollRunResultPayload = {
このテストデータの定義は、この箇所で適切であるか？
PipelineTestUtils.ts でもテストデータが定義されているが、どのような意図で定義箇所が使い分けられているか？

2024-12-02 02:11 UTC, tsuchiyama-araya commented on frontend/src/store/slice/Pipeline/Pipeline.test.ts
> +const pollRunResultPayload = {
ご指摘ありがとうございます。
createRunResultAndCancelFulfilledAction は共通で利用可能な関数として活用できるように、Pipeline.test.ts に移動しました。また、PipelineTestUtils.ts からは削除しております。
現在、この関数は引数を渡して呼び出す形になっています。

2024-12-02 02:21 UTC, tsuchiyama-araya commented on frontend/src/store/slice/Pipeline/Pipeline.test.ts
> +        createFulfilledActionWithRunPostData(runByCurrentUid)
ご指摘ありがとうございます。
こちら対応しました。

2024-12-02 02:39 UTC, itutu-tienday requested changes

2024-12-02 02:39 UTC, itutu-tienday commented on frontend/src/store/slice/Pipeline/PipelineTestUtils.ts
> +export const createRunResultAndCacelFulfilledAction = (
スペルミスあり
"Cacel" -> "Cancel"

2024-12-02 02:39 UTC, itutu-tienday commented on frontend/src/store/slice/Pipeline/Pipeline.test.ts
> +const pollRunResultPayload = {
> createRunResultAndCancelFulfilledAction は共通で利用可能な関数として活用できるように、

こちらからの指摘は、 `const pollRunResultPayload` に対してですが、認識に相違はないでしょうか？

2024-12-02 03:16 UTC, tsuchiyama-araya commented on frontend/src/store/slice/Pipeline/Pipeline.test.ts
> +const pollRunResultPayload = {
はい、pollRunResultPayload　を引数としてcreateRunResultAndCancelFulfilledActionに渡されています。

2024-12-02 03:28 UTC, tsuchiyama-araya commented on frontend/src/store/slice/Pipeline/PipelineTestUtils.ts
> +export const createRunResultAndCacelFulfilledAction = (
対応しました。
ありがとうございます。

2024-12-03 00:22 UTC, itutu-tienday commented on frontend/src/store/slice/Pipeline/Pipeline.test.ts
> +const pollRunResultPayload = {
上の件について、対処完了後、お知らせください。

2024-12-03 00:33 UTC, tsuchiyama-araya commented on frontend/src/store/slice/Pipeline/Pipeline.test.ts
> +const pollRunResultPayload = {
こちらは対応しました。
Pipeline Testを確認したところ、RunPost Dataは他のところにも利用されているので、
Pipeline.tsに外すのは難しいかと思いました。
そのため、RunPostDataと同じ使い方で、pollRunResultPayload をPipelineTestUtilsで定義して、
Pipeline Test.tsにImportする形にしました。

2024-12-03 02:21 UTC, itutu-tienday approved these changes

2024-12-03 03:08 UTC, merged