[No.203]Workflow を新しいIDでcopy する機能
arayabrain/barebone-studio pull request #496
Opened 2024-12-03 12:30 UTC by tsuchiyama-araya

【内容】
実装画面　→ RECORD画面

「RUN ALL」を実行すれば同じワークフローを作成できることは理解しているが、再実行が必要なため時間がかかる。
そのため、実行状態を保持したまま、新しいIDや名前でワークフローをコピーできる機能が欲しい。
Reproduce機能の一つのオプションとして実装するのが適切だと思われる。
→ 右上のDeleteボタンの横に「Duplicate」ボタンを追加する。

https://docs.google.com/spreadsheets/d/1x0vizVJK8U0GXuZyDPap0g-iri7xDX19/edit?gid=260426401#gid=260426401
No.203

2024-12-12 04:33 UTC, itutu-tienday requested changes

2024-12-13 02:25 UTC, tsuchiyama-araya commented on frontend/src/store/slice/Experiments/ExperimentsSlice.ts
> +      .addMatcher(isAnyOf(copyExperimentByList.fulfilled), (state) => {
> また単一のclassの判定に、addMatcher(isAnyOf( を指定している事由は？ （冗長ではないか）
ご指摘ありがとうございます。
申し訳ございませんが、こちらの質問は少し理解ができません。もう少し詳しく教えていただけませんか？

2024-12-13 02:40 UTC, itutu-tienday commented on frontend/src/store/slice/Experiments/ExperimentsSlice.ts
> +      .addMatcher(isAnyOf(copyExperimentByList.fulfilled), (state) => {
`addCase` と `addMatcher + isAnyOf ` の仕様を確認してください。
そのうえで、addMatcher の使用が適切であるのか、改めて判断してください。

2024-12-13 05:35 UTC, tsuchiyama-araya commented on studio/app/common/core/experiment/experiment_writer.py
> +            logger.info("Unique ID updated successfully.")
こちらは上記のTry/Exceptの対応で新しくなるので、
お手数ですが、そちらを再度ご確認お願い致します。

2024-12-13 05:37 UTC, tsuchiyama-araya commented on studio/app/common/routers/experiment.py
> +async def copy_experiment_list(workspace_id: str, copyItem: DeleteItem):
ご指摘ありがとうございます。
実装もれてました。
改修します

2024-12-16 00:08 UTC, tsuchiyama-araya commented on studio/app/common/core/experiment/experiment_writer.py
> +            config["unique_id"] = new_unique_id
私の認識だと、こちらだけで大丈夫かと思います。
一応Outputフォルダーの中にunique_idで検索すると、Experiment Yamlのみで記載されています。

2024-12-16 00:11 UTC, tsuchiyama-araya commented
@itutu-tienday 
ご指摘いただき、ありがとうございました。
ご指摘いただいた箇所を修正いたしましたので、
お手数をおかけしますが、再度ご確認いただけますと幸いです。

2024-12-16 09:48 UTC, itutu-tienday requested changes

2024-12-16 09:48 UTC, itutu-tienday commented on studio/app/common/core/experiment/experiment_writer.py
> +    def _update_experiment_config(
- [ ] 細かいですが、この関数のプリフィックスに "_" が付与されていますが、private scope の想定であれば、"__" が適当かと思われます
- [ ] また関数名が `update_experiment` 機能に対して名称が汎用的なため、もう少し機能を明示した名称がよさそうです。（「新しいunique_id（experimentのID）でデータを更新する」という機能ですよね）

2024-12-16 09:48 UTC, itutu-tienday commented on frontend/src/store/slice/Experiments/ExperimentsSlice.ts
> +      .addMatcher(isAnyOf(copyExperimentByList.fulfilled), (state) => {
こちらremindしておきます。

2024-12-16 09:48 UTC, itutu-tienday commented on studio/app/common/core/experiment/experiment_writer.py
> +            config["unique_id"] = new_unique_id
Evidence（更新されたexperiment.yamlの内容）を添付していただけますか？
※こちらの確認では、上で記載のように、unique_id の更新漏れがあるように見えます。
※もし不具合があった場合、テストケースにこの不具合を検知するためのテストケースを追加しておいてください。

2024-12-17 02:26 UTC, tsuchiyama-araya commented on frontend/src/store/slice/Experiments/ExperimentsSlice.ts
> +      .addMatcher(isAnyOf(copyExperimentByList.fulfilled), (state) => {
@itutu-tienday 
お疲れ様です。
こちらに関してですが、どのような指摘かが理解できないため、会話をお願いしても大丈夫でしょうか？
知識不足で申し訳ございません。

2024-12-17 02:26 UTC, tsuchiyama-araya commented on studio/app/common/core/experiment/experiment_writer.py
> +            config["unique_id"] = new_unique_id
Evidenceを添付しました。
お手数ですが、ご確認お願い致します。

2024-12-17 02:48 UTC, tsuchiyama-araya commented on studio/app/common/core/experiment/experiment_writer.py
> +    def _update_experiment_config(
こちら対応しました。
お手数ですが、ご確認お願い致します。

2024-12-17 07:19 UTC, itutu-tienday requested changes

2024-12-17 07:19 UTC, itutu-tienday commented on studio/app/common/core/experiment/experiment_writer.py
> +            for root, _, files in os.walk(directory):
os.walk の利用は冗長と見受けられる。
処理対象となるファイルが自明なのであれば、glob などで明確に指定すべき。（仕様が明瞭にもなる）

2024-12-17 07:19 UTC, itutu-tienday commented on studio/app/common/core/experiment/experiment_writer.py
> +                    if old_unique_id in content:
この判定はやや危険がある可能性あり。（想定しないマッチパターンも拾う可能性）
判定条件の精度を高めた方が良い。
→ どの位置に unique_id が含まれ得るか、仕様を整理の上、その条件で正規表現で指定し置換する形がベター。

2024-12-17 07:19 UTC, itutu-tienday commented on frontend/src/store/slice/Experiments/ExperimentsSlice.ts
> +      .addMatcher(isAnyOf(copyExperimentByList.fulfilled), (state) => {
最終的にrefactoring済みを確認。

2024-12-17 07:26 UTC, itutu-tienday commented on studio/app/common/core/experiment/experiment_writer.py
> +            for root, _, files in os.walk(directory):
こちらで適当な experiment の directory を id で grep してみたところ、pkl ファイルなどの中にも、idが含まれているようであることを確認。

※上記のケース（pklファイルなど）

```
$ grep -inrl "834359c6" * 
experiment.yaml
snakemake.yaml
suite2p_file_convert_sybncuz8n1/suite2p_file_convert.pkl
suite2p_file_convert_sybncuz8n1/suite2p/plane0/ops.npy
suite2p_registration_obwi55dmml/suite2p_registration.pkl
suite2p_roi_wavpgxg6co/suite2p_roi.pkl
```

2024-12-17 07:31 UTC, itutu-tienday commented on studio/app/common/core/experiment/experiment_writer.py
> +                    if old_unique_id in content:
こちらで適当な experiment の directory を id で grep してみたところ、pkl ファイルなどの中にも、idが含まれているようであることを確認。

※このケースは、想定されていたでしょうか？
※この状況を踏まえると、もしかすると、「1.copy」「2.copy元をdelete」「3.copy先を操作(workflow runなど)」の操作を行うと、pkl内のファイルパスがリンク切れとなり、エラーが生じるようなことは想定されないでしょうか？

```
$ grep -inrl "834359c6" * 
experiment.yaml
snakemake.yaml
suite2p_file_convert_sybncuz8n1/suite2p_file_convert.pkl
suite2p_file_convert_sybncuz8n1/suite2p/plane0/ops.npy
suite2p_registration_obwi55dmml/suite2p_registration.pkl
suite2p_roi_wavpgxg6co/suite2p_roi.pkl
```

2025-01-15 05:52 UTC, itutu-tienday requested changes

2025-01-15 05:52 UTC, itutu-tienday commented on studio/app/common/core/experiment/experiment_writer.py
> +                    if old_unique_id in content:
> この判定はやや危険がある可能性あり。（想定しないマッチパターンも拾う可能性）
> → どの位置に unique_id が含まれ得るか、仕様を整理の上、その条件で正規表現で指定し置換する形がベター。

まだ上記が対応されていない模様。（単純な str.replace が用いられている）
指摘の意図を踏まえ、改善策を適用してください。

2025-01-15 05:52 UTC, itutu-tienday commented on studio/app/common/core/experiment/experiment_writer.py
> +    def __update_yaml(self, file_path: str, old_id: str, new_id: str) -> None:
関数名（__update_xxx）がやや単純であり、関数名から機能が把握しづらく見える。 
用途（copy_data からしか参照されない関数でもある）を明確にした名称とする。

2025-01-15 05:52 UTC, itutu-tienday commented on studio/app/common/core/experiment/experiment_writer.py
> +    def __update_pickle(self, file_path: str, old_id: str, new_id: str) -> None:
他の `def __update_xxx' と同様、関数名を refactoring する

2025-01-15 05:52 UTC, itutu-tienday commented on studio/app/common/core/experiment/experiment_writer.py
> +    def __update_npy(self, file_path: str, old_id: str, new_id: str) -> None:
他の `def __update_xxx' と同様、関数名を refactoring する

2025-01-15 05:52 UTC, itutu-tienday commented on studio/app/common/core/experiment/experiment_writer.py
> +    def __replace_ids_recursive(
この処理（def copy_data からの呼び出し）は、自動テスト（想定通りに各データが置換されているかどうか）を用意しておくのがよいと思われる。

※自動テストの実装作業は、簡易に対応可能であればこのPR内で、多少の時間を要する場合は、別issueで対応を想定してください。

2025-01-15 05:52 UTC, itutu-tienday commented on studio/app/common/core/experiment/experiment_writer.py
> +    def __update_experiment_config_name(self, output_dir: str) -> bool:
他の `def __update_xxx' と同様、関数名を refactoring する

2025-01-15 05:52 UTC, itutu-tienday commented on studio/app/common/core/experiment/experiment_writer.py
> +                yaml.safe_dump(config, file)
他の箇所のyaml保存では、yaml の dump には `yaml.dump` が使用されています。
`yaml.safe_dump` の方が本来適切そうですが、箇所により使用されるyaml出力関数が異なるのは、あまり適切ではなさそうです。

ここで `yaml.safe_dump` を利用している明確な意図はありますか？
特に明確な意図がなければ、他の箇所とコードを統一しておいてください。

2025-01-15 05:52 UTC, itutu-tienday commented on studio/app/common/core/experiment/experiment_writer.py
> +                yaml.safe_dump(config, file)
ここで yaml dump すると、experiment.yaml 内の構造（key の order）が全体的に変更されています。
以下を参考に、構造を維持する調整を適用してください。
- f76722a

- [ ] また上記の仕様（yamlファイルの構造維持）を、テストケースにも追記しておいてください。

2025-01-19 23:52 UTC, tsuchiyama-araya commented on studio/app/common/core/experiment/experiment_writer.py
> +    def __replace_ids_recursive(
少し、お時間がかかる可能性があるので、こちらでIssueを作成しました。
https://github.com/arayabrain/barebone-studio/issues/559

2025-01-20 05:29 UTC, tsuchiyama-araya commented
@itutu-tienday 
お疲れ様です。
指摘していただいた内容を対応しました。
お手数ですが、再度ご確認お願い致します。

2025-01-20 08:15 UTC, itutu-tienday approved these changes

2025-01-20 08:15 UTC, itutu-tienday commented on studio/app/common/core/experiment/experiment_writer.py
> +                    if old_unique_id in content:
修正を確認

2025-01-20 23:45 UTC, merged