Fixing Conflicts Files With Develop Test and Develop Main
arayabrain/barebone-studio pull request #499
Opened 2024-12-04 03:56 UTC by tsuchiyama-araya

Fixing Conflicts Files With Develop Test and Develop Main

2024-12-04 04:49 UTC, itutu-tienday requested changes

2024-12-04 04:49 UTC, itutu-tienday commented on frontend/yarn.lock
>  "@babel/code-frame@^7.0.0", "@babel/code-frame@^7.10.4", "@babel/code-frame@^7.12.13", "@babel/code-frame@^7.16.0", "@babel/code-frame@^7.25.9", "@babel/code-frame@^7.26.0", "@babel/code-frame@^7.8.3
ここは、上のセクションと、同じ内容ではないか？
- おそらくmerge missの可能性（内容の重複）
- 他にも同様の箇所が多数ありそうか

2024-12-04 04:49 UTC, itutu-tienday commented on frontend/yarn.lock
>  "@babel/code-frame@^7.0.0", "@babel/code-frame@^7.10.4", "@babel/code-frame@^7.12.13", "@babel/code-frame@^7.16.0", "@babel/code-frame@^7.25.9", "@babel/code-frame@^7.26.0", "@babel/code-frame@^7.8.3
なおこのファイル（yarn.lock）の修正後、frontendの動作確認（run,build,test, ...）は行われていますか？
→ 動作確認、および yarn.lock のrefresh（再生成）は、行っておくべきではないか。

2024-12-10 05:15 UTC, whoisyuu commented on frontend/yarn.lock
>  "@babel/code-frame@^7.0.0", "@babel/code-frame@^7.10.4", "@babel/code-frame@^7.12.13", "@babel/code-frame@^7.16.0", "@babel/code-frame@^7.25.9", "@babel/code-frame@^7.26.0", "@babel/code-frame@^7.8.3
Merge Missです。一応動作確認はしましたが、
動作に問題なかったですが、これは異常なので、yarn.lock のRefreshを実行したいと思います。

2024-12-10 05:35 UTC, tsuchiyama-araya commented on frontend/yarn.lock
>  "@babel/code-frame@^7.0.0", "@babel/code-frame@^7.10.4", "@babel/code-frame@^7.12.13", "@babel/code-frame@^7.16.0", "@babel/code-frame@^7.25.9", "@babel/code-frame@^7.26.0", "@babel/code-frame@^7.8.3
Merge Missです。一応動作確認はしましたが、
動作に問題なかったですが、これは異常なので、yarn.lock のRefreshを実行したいと思います。

2024-12-10 06:25 UTC, itutu-tienday requested changes

2024-12-10 06:25 UTC, itutu-tienday commented on frontend/yarn.lock
> -"@babel/helper-builder-binary-assignment-operator-visitor@^7.25.9":
ここは削除で問題ない？

2024-12-10 06:25 UTC, itutu-tienday commented on frontend/yarn.lock
> -"@babel/helper-simple-access@^7.25.9":
ここは削除で問題ない？

2024-12-10 06:25 UTC, itutu-tienday commented on frontend/yarn.lock
> +"@types/react@*":
- `@types/react` が複数定義されているのは正しい？
- また React 19 (2024/12のメジャーリリース版) がインストールされている？

2024-12-10 06:33 UTC, tsuchiyama-araya commented on frontend/yarn.lock
> -"@babel/helper-builder-binary-assignment-operator-visitor@^7.25.9":
指摘ありがとうございます。
一応、テストケースなども通っていることが確認できています。
また、どこかで使用されているのかなと思いましたが、確認したところ使用用途としてはないかと思います。
そのため、それは削除で大丈夫かと思います。

2024-12-10 06:42 UTC, itutu-tienday commented on frontend/yarn.lock
> +"@types/react@*":
上記ご確認ください （Remind）

2024-12-11 04:29 UTC, tsuchiyama-araya commented on frontend/yarn.lock
> +"@types/react@*":
こちらは対応しました。
お手数ですが、ご確認お願い致します。

2024-12-17 05:45 UTC, itutu-tienday commented
Close as the same response has already been addressed in below
- #529.

2024-12-17 05:46 UTC, closed without merging