関数とパラメーターに説明のリンク追加
arayabrain/barebone-studio pull request #534
Opened 2024-12-23 03:33 UTC by tsuchiyama-araya

【内容】
#510 
パラメーターのタイトルと関数の説明にリンクで説明に遷移させました。

2024-12-23 04:03 UTC, itutu-tienday requested changes

2024-12-23 04:03 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/RightDrawer/AlgorithmParamForm.tsx
> +      <a
外部のhelp pageへジャンプする仕様を明示するため、
関数名の横などに icon + tooltip("Jump to detail page" など) を配置して、そこからジャンプするとよいかもしれません。

- icon例
  - https://mui.com/material-ui/material-icons/?selected=Info
  - https://mui.com/material-ui/material-icons/?selected=Launch

2024-12-24 01:21 UTC, tsuchiyama-araya commented on frontend/src/components/Workspace/FlowChart/RightDrawer/index.tsx
> +      case RIGHT_DRAWER_MODE.PARAM_FORM:
ご確認、ありがとうございます。
リンクが不要だと考えた理由を教えていただけませんか？

2024-12-24 01:42 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/RightDrawer/index.tsx
> +      case RIGHT_DRAWER_MODE.PARAM_FORM:
> リンクが不要だと考えた理由を教えてもらえませんか？

以下で掲載されるリンクと重複しており、リンクの機能として冗長さを感じました。
https://github.com/arayabrain/barebone-studio/pull/534/files/d6580a3f050f5a25786077a6c7c9a8e6ddeb0ff0#diff-ef77fa440e74bff5b4680151eef3c8c5e269ad0227b247d659204e99c49c71f1R29

2024-12-24 04:43 UTC, tsuchiyama-araya commented on frontend/src/components/Workspace/FlowChart/RightDrawer/index.tsx
> +      case RIGHT_DRAWER_MODE.PARAM_FORM:
はい、おっしゃる通りです。
Paramsの場合はパラメーターにリンクさせるようにします。

2024-12-24 04:43 UTC, tsuchiyama-araya commented on frontend/src/components/Workspace/FlowChart/RightDrawer/AlgorithmParamForm.tsx
> +      <a
対応します。
ありがとうございます。

2024-12-24 09:10 UTC, itutu-tienday requested changes

2024-12-24 09:10 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/RightDrawer/AlgorithmParamForm.tsx
> +      <a
基本的にはOKそうです。

なお後以下、微調整いただけるとよさそうです。

- {algoName} と icon の間に余白を設ける（iconの視認性を上げる）

2024-12-24 09:10 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/RightDrawer/index.tsx
> +  const readTheDocsUrl =
"readTheDocsUrl" という変数名なのであれば、URLの値はもう少し一般化しておくと良さそうです
例） `https://optinist.readthedocs.io/en/latest` までなど

2024-12-25 06:05 UTC, itutu-tienday reviewed
- 現時点では、指摘事項はall resolevedを確認
- なおドキュメントへのリンクURLは仮状態と思われるため、Approve は一旦保留
  - ドキュメント担当者と URLを決定の上、コードへ反映してください

2025-02-03 23:55 UTC, tsuchiyama-araya commented
こちらのPRがCloseしたら、こちらのPRもCloseします。
https://github.com/arayabrain/barebone-studio/pull/466

2025-02-27 08:26 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/RightDrawer/AlgorithmParamForm.tsx
> +  const parameterUrl = `https://optinist.readthedocs.io/en/latest/specifications/algorithm_nodes.html#${formattedAlgoName}`
リンク成功のテストを行って下さい
※少し確認してみたところ、リンク切れが多数ありそうです（リンク先にコンテンツはあります）

2025-02-27 08:26 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/RightDrawer/AlgorithmParamForm.tsx
> +      <div style={{ display: "flex" }}>
マウスホバーでアイコンを切り替えて下さい（他の箇所と同様）

2025-02-28 02:39 UTC, tsuchiyama-araya commented on frontend/src/components/Workspace/FlowChart/RightDrawer/AlgorithmParamForm.tsx
> +  const parameterUrl = `https://optinist.readthedocs.io/en/latest/specifications/algorithm_nodes.html#${formattedAlgoName}`
こちら対応できました。

2025-02-28 02:39 UTC, tsuchiyama-araya commented on frontend/src/components/Workspace/FlowChart/RightDrawer/AlgorithmParamForm.tsx
> +      <div style={{ display: "flex" }}>
ホバー時に表示するアイコンについて、どのようなものが適切でしょうか？
現時点でアイコンを探してみましたが、適したものが見つかりませんでした。
現在はToolTipを使用しており、ホバー時に「Check Documentation」と表示されるため、これで十分かとも考えています。

もう少し具体的にご説明いただけると助かります。
よろしくお願いいたします。

2025-02-28 02:42 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/RightDrawer/AlgorithmParamForm.tsx
> +      <div style={{ display: "flex" }}>
> もう少し具体的にご説明いただけると助かります。

他のボタン系では、ほぼマウスカーソルが切り替わっていると思われますが（指アイコン）、どのあたりがご不明でしょうか？

2025-03-03 01:35 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/RightDrawer/AlgorithmParamForm.tsx
> +  const parameterUrl = `https://optinist.readthedocs.io/en/latest/specifications/algorithm_nodes.html#${formattedAlgoName}`
すべて確認していませんが、複数件のリンク切れがまだあるようです。
→ lccd_cell_detection, cnmf_multisession, ...

すべてのNode Paramのリンク成功を、再チェックしてください。

2025-03-03 08:12 UTC, tsuchiyama-araya commented on frontend/src/components/Workspace/FlowChart/RightDrawer/AlgorithmParamForm.tsx
> +  const parameterUrl = `https://optinist.readthedocs.io/en/latest/specifications/algorithm_nodes.html#${formattedAlgoName}`
@itutu-tienday 
こちら対応と確認できました。
お手数ですが、ご確認お願いいたします。

2025-03-03 08:46 UTC, itutu-tienday requested changes

2025-03-03 08:46 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/RightDrawer/AlgorithmParamForm.tsx
> +  const parameterUrl = `https://optinist.readthedocs.io/en/latest/specifications/algorithm_nodes.html#${formattedAlgoName}`
再確認してください
https://optinist.readthedocs.io/en/latest/specifications/algorithm_nodes.html#roi-fluo-from-hdf5

2025-03-03 08:51 UTC, tsuchiyama-araya commented on frontend/src/components/Workspace/FlowChart/RightDrawer/AlgorithmParamForm.tsx
> +  const parameterUrl = `https://optinist.readthedocs.io/en/latest/specifications/algorithm_nodes.html#${formattedAlgoName}`
なるほど、roi_fluo_from_hdf5ですね。
こちらは、まだ記載されていないのですが、こちらのブランチで対応したほうが良いのでしょうか？
また、DocsとParamsリンクのリリースは同時で行いますか？

2025-03-03 08:56 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/RightDrawer/AlgorithmParamForm.tsx
> +  const parameterUrl = `https://optinist.readthedocs.io/en/latest/specifications/algorithm_nodes.html#${formattedAlgoName}`
ドキュメントは用意しないのですか？
Node作成者・ドキュメント編集者間で、調整してください。

2025-03-03 09:10 UTC, itutu-tienday approved these changes
まだリンク切れが確認されますが、1箇所のみのため、修正のmergeを優先し、approveします。
上記リンク切れについて、ドキュメント更新担当者と調整の上、最終的にリンク切れを解消しておいてください。

2025-03-03 11:14 UTC, merged