TODO [No.129]Function with the ability to select cells (Data filter B…
arayabrain/barebone-studio pull request #536
Opened 2024-12-23 08:45 UTC by sanglevinh

…utton)

2025-01-06 09:56 UTC, itutu-tienday requested changes

2025-01-06 09:56 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/FlowChartNode/AlgorithmNode.tsx
> +            Filter
If the Param of the Node before the Node with the Filter Button is changed, the Filter Button will not be disabled.
-> If the Node with the Filter Button is the target of re-execution, the Filter Button will be disabled.
*See QA sheet No.4

2025-01-06 09:56 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/FlowChartNode/AlgorithmNode.tsx
> +            Filter
When the Filter is updated, the Node in question is highlighted as an update target, but the subsequent Node is not highlighted.
In the actual process, the subsequent Node seems to be the target of execution in the backend, but we would like it to be highlighted as the target of execution in the frontend as well.

![image](https://github.com/user-attachments/assets/acdf2f4f-414d-49e7-9277-f68fbc30ecc8)

2025-01-06 11:19 UTC, sanglevinh commented on frontend/src/components/Workspace/FlowChart/FlowChartNode/AlgorithmNode.tsx
> +            Filter
@itutu-tienday Should I reset the filter parameters to their initial state or clear them completely?

2025-01-07 02:30 UTC, milesAraya requested changes
Currently the filter box has bugs in the input

- [x] Cannot delete "0"
- [ ] Cannot input commas into ROI
- [ ] Actual data dims should be used for placeholders
- [ ] Filter box parameters are not passed to the subsequent analysis. This is the whole point of the filter box. If dim 1:500 is selected, only that data should be used for the next step of analysis. This will allow users to save time by only performing analysis on certain important sections of the data. For PCA it will also change the results. This is a top priority. 
- [ ] Fluorescence and ROI windows should be shown simultaneously and side-by-side (this is lower priority as user could still manage to use the filter box without this. However, it was still in the request)

2025-01-07 02:30 UTC, milesAraya commented on frontend/src/components/Workspace/FlowChart/Dialog/AlgorithmOutputDialog.tsx
> +        placeholder="1:128"
If you input "1:0", you cannot delete the 0 using backspace. You need to highlight the whole text and delete, or add some more numbers and then delete those

2025-01-07 02:30 UTC, milesAraya commented on frontend/src/components/Workspace/FlowChart/Dialog/AlgorithmOutputDialog.tsx
> +      <Input inputProps={{ style: { textAlign: "center" } }} {...p} />
I think in the powerpoint request, there were 2 side-by-side windows, with ROI and fluorescence both visible.

2025-01-07 02:30 UTC, milesAraya commented on frontend/src/components/Workspace/FlowChart/Dialog/AlgorithmOutputDialog.tsx
> +      dim1: getData(dataFilterParams?.dim1),
It would be good if these dimensions, from the real data, are used in the placeholders
placeholder="1:1000" -> placeholder="1:dim3"

2025-01-07 02:30 UTC, milesAraya commented on frontend/src/store/slice/AlgorithmNode/AlgorithmNodeSlice.ts
> +      action: PayloadAction<{
When i choose filter settings, these do not seem to be passed on to the next nodes. 
Here i select ROI 1:30
<img width="587" alt="Screenshot 2025-01-07 at 11 21 03" src="https://github.com/user-attachments/assets/62307b46-368b-4891-89e5-87e3dbd106cc" />

But in the ETA visualise window all the ROI are present (e.g. 121). Only ROI 1:30 should be present

<img width="540" alt="Screenshot 2025-01-07 at 11 20 55" src="https://github.com/user-attachments/assets/a6caf730-be56-46d9-8e2e-03ded5056236" />

And the fluorescence dim was selected to be 1:500, but in the flourescence window 1:2000 are still visible
<img width="506" alt="image" src="https://github.com/user-attachments/assets/bd1f9bbc-0ce1-4536-b125-c780c550a539" />

2025-01-07 03:30 UTC, sanglevinh commented on frontend/src/store/slice/AlgorithmNode/AlgorithmNodeSlice.ts
> +      action: PayloadAction<{
@milesAraya 
When you change the filter parameters, please run it again to update the data. The changes will not be reflected until you run it again.

2025-01-07 03:58 UTC, sanglevinh commented on frontend/src/components/Workspace/FlowChart/Dialog/AlgorithmOutputDialog.tsx
> +      <Input inputProps={{ style: { textAlign: "center" } }} {...p} />
> I think in the powerpoint request, there were 2 side-by-side windows, with ROI and fluorescence both visible.

@milesAraya 
Currently, I see that the description in the PowerPoint about the UI is similar to the output UI, so I am reusing this UI for now. If we follow the PowerPoint layout, the UI will only display two side-by-side panels, right? Because the output UI has quite a few tabs.

2025-01-07 05:53 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/FlowChartNode/AlgorithmNode.tsx
> +            Filter
If the Node with the Filter button is re-run, please set the following state.
- Disable the Filter button
- Reset the previous filter contents (because the data may change when the node is re-run)

2025-01-07 05:58 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/Dialog/AlgorithmOutputDialog.tsx
> +        placeholder="1:128"
This conversation will be unresolved because the reviewer has not yet checked it.
*The reviewer should resolve the conversation.

2025-01-07 06:47 UTC, sanglevinh commented on frontend/src/components/Workspace/FlowChart/FlowChartNode/AlgorithmNode.tsx
> +            Filter
@itutu-tienday I have made the change. When the parent node's parameters change, I will revert the data filter to its original value, originalDataFilterValue

2025-01-07 06:49 UTC, sanglevinh commented on frontend/src/components/Workspace/FlowChart/Dialog/AlgorithmOutputDialog.tsx
> +        placeholder="1:23,50:52"
@milesAraya I have fixed it.

2025-01-07 06:49 UTC, sanglevinh commented on frontend/src/components/Workspace/FlowChart/Dialog/AlgorithmOutputDialog.tsx
> +        placeholder="1:128"
@milesAraya I have fixed it.

2025-01-07 11:32 UTC, itutu-tienday requested changes

2025-01-07 11:32 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/Dialog/AlgorithmOutputDialog.tsx
> +    <Box display="flex" gap={2} textAlign="center" pt={2}>
Could you place the following buttons
- APPLY
- CANCEL
- RESET

Design documents are being updated
- https://docs.google.com/presentation/d/1ksXS7NZRe5BKnIyS3v2Ird539OmulOMD/edit#slide=id.p3

2025-01-07 11:32 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/FlowChartNode/AlgorithmNode.tsx
> +            Filter
If I apply a Filter, can I have the Node's Hilight applied only to the Filter button? (Node itself will remain white)

The design document has been updated.
- https://docs.google.com/presentation/d/1ksXS7NZRe5BKnIyS3v2Ird539OmulOMD/edit#slide=id.p3

If the implementation is going to be complicated, please contact us.

2025-01-07 11:32 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/Dialog/AlgorithmOutputDialog.tsx
> +      <InputDim
Validate must be applied to input values

- Numeric values start from 1
- Compare the value to a larger or smaller value
- Check the upper limit of the numerical value
  - This requires obtaining the upper limit of the actual data. If this is difficult to handle, please contact us.

2025-01-24 03:30 UTC, itutu-tienday commented on studio/app/common/core/experiment/experiment.py
> +            output_relative_dir = re.sub(f"^{DIRPATH.OUTPUT_DIR}/", "", self.output_dir)
@sanglevinh 
I assume that the fixes in this area have already been reflected in develop-main.
I would like to clear unnecessary diffs in order to clear up the modified areas this time.
*Will merge develop-main into this PR branch clear this diff?

2025-01-24 03:50 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/FlowChartNode/AlgorithmNode.tsx
> +      ["suite2p_roi", "caiman_cnmf", "lccd_cell_detection"].includes(
caiman_cnmfe should also be included in the Filter.

2025-01-24 07:28 UTC, itutu-tienday requested changes

2025-01-24 07:28 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/Dialog/BoxFilter.tsx
> +            APPLY
If there is an error (invalid format, etc.) in the input field, the APPLY button should not be pressed.

2025-01-24 07:28 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/Dialog/BoxFilter.tsx
> +          <InputDim
When I follow the procedure below to open the Filter Dialog multiple times, the value in the Input field set in the previous Filter Dialog seems to remain in the placeholder text, as shown in the screenshot.

1. Filter Dialog open
2. Filter Apply
3. Filter Dialog re-open

The expected behavior is that the placeholder is basically always “0:max-value”.
![image](https://github.com/user-attachments/assets/42ddb5fb-4d58-47ca-a51b-88eab95f63c9)

2025-02-18 10:49 UTC, sanglevinh commented on frontend/src/components/Workspace/FlowChart/Dialog/AlgorithmOutputDialog.tsx
> +      <Input inputProps={{ style: { textAlign: "center" } }} {...p} />
I have fixed it.

2025-02-18 10:50 UTC, sanglevinh commented on frontend/src/components/Workspace/FlowChart/Dialog/AlgorithmOutputDialog.tsx
> +      dim1: getData(dataFilterParams?.dim1),
@milesAraya  I have fixed it.

2025-02-18 10:51 UTC, sanglevinh commented on frontend/src/store/slice/AlgorithmNode/AlgorithmNodeSlice.ts
> +      action: PayloadAction<{
@milesAraya I have fixed it.

2025-02-18 10:52 UTC, sanglevinh commented on studio/app/common/core/experiment/experiment.py
> +            output_relative_dir = re.sub(f"^{DIRPATH.OUTPUT_DIR}/", "", self.output_dir)
@itutu-tienday  I have fixed it.

2025-02-18 11:03 UTC, sanglevinh commented on frontend/src/components/Workspace/FlowChart/Dialog/BoxFilter.tsx
> +            APPLY
@itutu-tienday I have fixed it.

2025-02-18 11:07 UTC, sanglevinh commented on frontend/src/components/Workspace/FlowChart/Dialog/BoxFilter.tsx
> +          <InputDim
@itutu-tienday I can no longer reproduce this error. It seems it has been fixed. Could you please test it again?

2025-02-18 11:09 UTC, sanglevinh commented
> @sanglevinh Please check the pending status comments.

Sorry for the late check. I have fixed everything. Could you please test it again?

2025-02-18 11:32 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/Dialog/BoxFilter.tsx
> +          <InputDim
@sanglevinh 
In the meantime, I will send you a video reproduction.
- https://github.com/user-attachments/assets/3589f4d4-df05-4fd3-aede-545cbd05bc47

- In the last dialog display, the placeholder for roi is supposed to be “0:4” (original size), but it is “0:3” which was entered just before.
- However, since it is actually possible to enter “0:4” and Reset is possible, the content does not have much impact.

2025-02-19 03:51 UTC, sanglevinh commented on frontend/src/components/Workspace/FlowChart/Dialog/BoxFilter.tsx
> +          <InputDim
@itutu-tienday I have fixed it.

2025-02-19 08:42 UTC, itutu-tienday approved these changes

2025-02-19 08:51 UTC, milesAraya approved these changes

2025-02-20 00:09 UTC, merged