[BE] Function with the ability to select cells (Data filter Button)
arayabrain/barebone-studio pull request #537
Opened 2024-12-23 09:05 UTC by tuanna26

2025-01-07 12:10 UTC, itutu-tienday requested changes

2025-01-07 12:10 UTC, itutu-tienday commented on studio/app/common/core/rules/runner.py
Please merge the following branches (as of 7/1)
`feature/resolve-abnormal-workflow`

2025-01-07 12:10 UTC, itutu-tienday commented on studio/app/common/core/rules/runner.py
This is a minor request, but please adjust the branch name
- Branch name that shows correspondence with FE branch
  - `feature/516_data-filter_be` etc.

2025-01-07 12:10 UTC, itutu-tienday commented on studio/app/common/core/rules/runner.py
> +            dataFilterParam = DataFilterParam(**__rule.dataFilterParam)
Can you explain a little about the logic (process flow) of this part?

2025-01-08 03:56 UTC, tuanna26 commented on studio/app/common/core/rules/runner.py
> +            dataFilterParam = DataFilterParam(**__rule.dataFilterParam)
When the filter parameters are passed through the "RUN" action, I check if this node's pickle file exists to filter. If it exists, I copy a backup of it because snakemake will delete the output file in runtime if it detects the parameter has changed.

In this part, if the filter parameter is not empty and a backup path exists, filtering will be performed based on the backup output data.

2025-01-08 03:59 UTC, closed without merging

2025-01-08 04:04 UTC, tuanna26 commented on studio/app/common/core/rules/runner.py
@itutu-tienday 
Renaming branch will close this PR, I opened https://github.com/arayabrain/barebone-studio/pull/546. 
![image](https://github.com/user-attachments/assets/1e64205d-b102-410c-a2a6-beae6f66846d)